DROP DATABASE IF EXISTS exe9;
CREATE DATABASE exe9;
USE exe9;

CREATE TABLE CLIENTES (
DNI CHAR(9),
Nombre VARCHAR(30),
Apellidos VARCHAR(30),
Telefono CHAR(9),
Email VARCHAR(20),
PRIMARY KEY (DNI)
);

CREATE TABLE TIENDAS (
Nombre VARCHAR(20),
Provincia CHAR(10),
Localidad CHAR(10),
Dirección VARCHAR(20),
Telefono CHAR(9),
DiaApertura DATE,
DiaCierre DATE,
HoraApertura TIME,
HoraCierre TIME,
PRIMARY KEY (Nombre)
);

CREATE TABLE OPERADORAS (
Nombre VARCHAR(20),
ColorLogo MEDIUMINT(10),
PorcentajeCobertura INT(3), 
FrecuenciaGSM INT(3),
PaginaWeb CHAR(30),
PRIMARY KEY(Nombre)
);

CREATE TABLE TARIFAS (
Nombre VARCHAR(20),
Nombre_OPERADORAS VARCHAR(20),
TamañoDatos FLOAT,
TipoDatos CHAR(10),
MinutosGratis INT(10),
SMSGratis BIT,
PRIMARY KEY (Nombre),
CONSTRAINT FK_OPERADORAS
FOREIGN KEY (Nombre_OPERADORAS) REFERENCES OPERADORAS(Nombre)
);

CREATE TABLE MOVILES (
Marca VARCHAR(20),
Modelo VARCHAR(20),
Descripcion TINYBLOB,
SO CHAR(10),
RAM char(10),
PulgadasPantalla INT(10),
CamaraMpx INT(10),
PRIMARY KEY (Marca,Modelo)
);

CREATE TABLE MOVIL_LIBRE (
Marca_MOVILES VARCHAR(20),
Modelo_MOVILES VARCHAR(20),
Nombre_OPERADORES VARCHAR(20),
precio int,
CONSTRAINT FK_MOVILES
FOREIGN KEY (Marca_MOVILES,Modelo_MOVILES) REFERENCES MOVILES(Marca,Modelo)
);

CREATE TABLE MOVIL_CONTRATO (
Marca_MOVILES VARCHAR(20),
Modelo_MOVILES VARCHAR(20),
Nombre_OPERADORAS VARCHAR(20),
CONSTRAINT FK_MOVIL
FOREIGN KEY (Marca_MOVILES,Modelo_MOVILES) REFERENCES MOVILES(Marca,Modelo),
FOREIGN KEY (Nombre_OPERADORAS) REFERENCES OPERADORAS(Nombre)
);

CREATE TABLE OFERTAS (
Nombre_OPERADORAS_TARIFAS VARCHAR(20),
Nombre_TARIFAS VARCHAR(20),
Marca_MOVIL_CONTRATO VARCHAR(20),
Modelo_MOVIL_CONTRATO VARCHAR(20),
CONSTRAINT FK_OFERTAS
FOREIGN KEY (Nombre_OPERADORAS_TARIFAS) REFERENCES TARIFAS(Nombre_OPERADORAS),
FOREIGN KEY (Nombre_TARIFAS) REFERENCES TARIFAS(Nombre),
FOREIGN KEY (Marca_MOVIL_CONTRATO,Modelo_MOVIL_CONTRATO) REFERENCES MOVIL_CONTRATO(Marca_MOVILES,Modelo_MOVILES)
);

CREATE TABLE COMPRAS (
DNI_Cliente CHAR(9),
Nombre_Tienda VARCHAR(20),
Marca_MOVILES_LIBRE VARCHAR(20),
Modelo_MOVILES_LIBRE VARCHAR(20),
Dia DATE,
CONSTRAINT FK_COMPRAS
FOREIGN KEY (DNI_Cliente) REFERENCES CLIENTES(DNI),
FOREIGN KEY (Nombre_Tienda) REFERENCES TIENDAS(Nombre),
FOREIGN KEY (Marca_MOVILES_LIBRE,Modelo_MOVILES_LIBRE) REFERENCES MOVIL_LIBRE(Marca_MOVILES,Modelo_MOVILES)
);

CREATE TABLE CONTRATOS (
DNI_Cliente CHAR(9),
Nombre_Tienda VARCHAR(20),
Nombre_OPERADORAS_TARIFAS_OFERTAS VARCHAR(20),
Nombre_TARIFAS_OFERTAS VARCHAR(20),
Marca_MOVILES_OFERTAS VARCHAR(20),
Modelo_MOVILES_OFERTAS VARCHAR(20),
Dia DATE,
CONSTRAINT FK_CONTRATOS
FOREIGN KEY (DNI_Cliente) REFERENCES CLIENTES(DNI),
FOREIGN KEY (Nombre_Tienda) REFERENCES TIENDAS(Nombre)
/*FOREIGN KEY    (Nombre_OPERADORAS_TARIFAS_OFERTAS,
		Nombre_TARIFAS_OFERTAS,
		Marca_MOVILES_OFERTAS,
		Modelo_MOVILES_OFERTAS)  
REFERENCES OFERTAS
		(Nombre_OPERADORAS_TARIFAS,
		Nombre_TARIFAS,
		Marca_MOVIL_CONTRATO,
		Modelo_MOVIL_CONTRATO)
*/);




